string replacement v2 run

diff --git a/perf/Makefile.in b/perf/Makefile.in
--- a/perf/Makefile.in
+++ b/perf/Makefile.in
@@ -14,7 +14,7 @@
 
 @SET_MAKE@
 
-# GTK+ - The GIMP Toolkit
+# BTK+ - The GIMP Toolkit
 
 VPATH = @srcdir@
 am__is_gnu_make = { \
@@ -74,8 +74,8 @@ am__make_dryrun = (target_option=n; $(am__make_running_with_option))
 am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
 pkgdatadir = $(datadir)/@PACKAGE@
 pkgincludedir = $(includedir)/@PACKAGE@
-pkglibdir = $(libdir)/@PACKAGE@
-pkglibexecdir = $(libexecdir)/@PACKAGE@
+pkbunnylibdir = $(libdir)/@PACKAGE@
+pkbunnylibexecdir = $(libexecdir)/@PACKAGE@
 am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
 install_sh_DATA = $(install_sh) -c -m 644
 install_sh_PROGRAM = $(install_sh) -c
@@ -103,13 +103,13 @@ CONFIG_HEADER = $(top_builddir)/config.h
 CONFIG_CLEAN_FILES =
 CONFIG_CLEAN_VPATH_FILES =
 PROGRAMS = $(noinst_PROGRAMS)
-am_testperf_OBJECTS = appwindow.$(OBJEXT) gtkwidgetprofiler.$(OBJEXT) \
+am_testperf_OBJECTS = appwindow.$(OBJEXT) btkwidgetprofiler.$(OBJEXT) \
 	main.$(OBJEXT) marshalers.$(OBJEXT) textview.$(OBJEXT) \
 	treeview.$(OBJEXT) typebuiltins.$(OBJEXT)
 testperf_OBJECTS = $(am_testperf_OBJECTS)
 am__DEPENDENCIES_1 =
-am__DEPENDENCIES_2 = $(top_builddir)/gdk/$(gdktargetlib) \
-	$(top_builddir)/gtk/$(gtktargetlib) $(am__DEPENDENCIES_1)
+am__DEPENDENCIES_2 = $(top_builddir)/bdk/$(bdktargetlib) \
+	$(top_builddir)/btk/$(btktargetlib) $(am__DEPENDENCIES_1)
 AM_V_lt = $(am__v_lt_@AM_V@)
 am__v_lt_ = $(am__v_lt_@AM_DEFAULT_V@)
 am__v_lt_0 = --silent
@@ -130,7 +130,7 @@ DEFAULT_INCLUDES = -I.@am__isrc@ -I$(top_builddir)
 depcomp = $(SHELL) $(top_srcdir)/depcomp
 am__maybe_remake_depfiles = depfiles
 am__depfiles_remade = ./$(DEPDIR)/appwindow.Po \
-	./$(DEPDIR)/gtkwidgetprofiler.Po ./$(DEPDIR)/main.Po \
+	./$(DEPDIR)/btkwidgetprofiler.Po ./$(DEPDIR)/main.Po \
 	./$(DEPDIR)/marshalers.Po ./$(DEPDIR)/textview.Po \
 	./$(DEPDIR)/treeview.Po ./$(DEPDIR)/typebuiltins.Po
 am__mv = mv -f
@@ -186,16 +186,16 @@ AMTAR = @AMTAR@
 AM_DEFAULT_VERBOSITY = @AM_DEFAULT_VERBOSITY@
 AR = @AR@
 AS = @AS@
-ATK_PREFIX = @ATK_PREFIX@
+BATK_PREFIX = @BATK_PREFIX@
 AUTOCONF = @AUTOCONF@
 AUTOHEADER = @AUTOHEADER@
 AUTOMAKE = @AUTOMAKE@
 AWK = @AWK@
 BASE_DEPENDENCIES_CFLAGS = @BASE_DEPENDENCIES_CFLAGS@
 BASE_DEPENDENCIES_LIBS = @BASE_DEPENDENCIES_LIBS@
-CAIRO_BACKEND_CFLAGS = @CAIRO_BACKEND_CFLAGS@
-CAIRO_BACKEND_LIBS = @CAIRO_BACKEND_LIBS@
-CAIRO_PREFIX = @CAIRO_PREFIX@
+BAIRO_BACKEND_CFLAGS = @BAIRO_BACKEND_CFLAGS@
+BAIRO_BACKEND_LIBS = @BAIRO_BACKEND_LIBS@
+BAIRO_PREFIX = @BAIRO_PREFIX@
 CATALOGS = @CATALOGS@
 CATOBJEXT = @CATOBJEXT@
 CC = @CC@
@@ -232,52 +232,52 @@ EGREP = @EGREP@
 EXEEXT = @EXEEXT@
 EXE_MANIFEST_ARCHITECTURE = @EXE_MANIFEST_ARCHITECTURE@
 FGREP = @FGREP@
-GAIL_INET_LIBS = @GAIL_INET_LIBS@
-GAIL_LT_CURRENT_MINUS_AGE = @GAIL_LT_CURRENT_MINUS_AGE@
-GAIL_LT_VERSION_INFO = @GAIL_LT_VERSION_INFO@
-GDK_DEP_CFLAGS = @GDK_DEP_CFLAGS@
-GDK_DEP_LIBS = @GDK_DEP_LIBS@
-GDK_EXTRA_CFLAGS = @GDK_EXTRA_CFLAGS@
-GDK_EXTRA_LIBS = @GDK_EXTRA_LIBS@
-GDK_PACKAGES = @GDK_PACKAGES@
-GDK_PIXBUF_CSOURCE = @GDK_PIXBUF_CSOURCE@
-GDK_PIXBUF_LIBS = @GDK_PIXBUF_LIBS@
-GDK_WLIBS = @GDK_WLIBS@
+BAIL_INET_LIBS = @BAIL_INET_LIBS@
+BAIL_LT_CURRENT_MINUS_AGE = @BAIL_LT_CURRENT_MINUS_AGE@
+BAIL_LT_VERSION_INFO = @BAIL_LT_VERSION_INFO@
+BDK_DEP_CFLAGS = @BDK_DEP_CFLAGS@
+BDK_DEP_LIBS = @BDK_DEP_LIBS@
+BDK_EXTRA_CFLAGS = @BDK_EXTRA_CFLAGS@
+BDK_EXTRA_LIBS = @BDK_EXTRA_LIBS@
+BDK_PACKAGES = @BDK_PACKAGES@
+BDK_PIXBUF_CSOURCE = @BDK_PIXBUF_CSOURCE@
+BDK_PIXBUF_LIBS = @BDK_PIXBUF_LIBS@
+BDK_WLIBS = @BDK_WLIBS@
 GETTEXT_PACKAGE = @GETTEXT_PACKAGE@
-GLIB_CFLAGS = @GLIB_CFLAGS@
-GLIB_COMPILE_RESOURCES = @GLIB_COMPILE_RESOURCES@
-GLIB_GENMARSHAL = @GLIB_GENMARSHAL@
-GLIB_LIBS = @GLIB_LIBS@
-GLIB_MKENUMS = @GLIB_MKENUMS@
-GLIB_PREFIX = @GLIB_PREFIX@
-GMODULE_CFLAGS = @GMODULE_CFLAGS@
-GMODULE_LIBS = @GMODULE_LIBS@
+BUNNYLIB_CFLAGS = @BUNNYLIB_CFLAGS@
+BUNNYLIB_COMPILE_RESOURCES = @BUNNYLIB_COMPILE_RESOURCES@
+BUNNYLIB_GENMARSHAL = @BUNNYLIB_GENMARSHAL@
+BUNNYLIB_LIBS = @BUNNYLIB_LIBS@
+BUNNYLIB_MKENUMS = @BUNNYLIB_MKENUMS@
+BUNNYLIB_PREFIX = @BUNNYLIB_PREFIX@
+BMODULE_CFLAGS = @BMODULE_CFLAGS@
+BMODULE_LIBS = @BMODULE_LIBS@
 GMOFILES = @GMOFILES@
 GMSGFMT = @GMSGFMT@
-GOBJECT_QUERY = @GOBJECT_QUERY@
+BOBJECT_QUERY = @BOBJECT_QUERY@
 GREP = @GREP@
-GTKDOC_CHECK = @GTKDOC_CHECK@
-GTKDOC_CHECK_PATH = @GTKDOC_CHECK_PATH@
-GTKDOC_DEPS_CFLAGS = @GTKDOC_DEPS_CFLAGS@
-GTKDOC_DEPS_LIBS = @GTKDOC_DEPS_LIBS@
-GTKDOC_MKPDF = @GTKDOC_MKPDF@
-GTKDOC_REBASE = @GTKDOC_REBASE@
-GTK_API_VERSION = @GTK_API_VERSION@
-GTK_BINARY_AGE = @GTK_BINARY_AGE@
-GTK_BINARY_VERSION = @GTK_BINARY_VERSION@
-GTK_DEBUG_FLAGS = @GTK_DEBUG_FLAGS@
-GTK_DEP_CFLAGS = @GTK_DEP_CFLAGS@
-GTK_DEP_LIBS = @GTK_DEP_LIBS@
-GTK_EXTRA_CFLAGS = @GTK_EXTRA_CFLAGS@
-GTK_EXTRA_LIBS = @GTK_EXTRA_LIBS@
-GTK_INTERFACE_AGE = @GTK_INTERFACE_AGE@
-GTK_MAJOR_VERSION = @GTK_MAJOR_VERSION@
-GTK_MICRO_VERSION = @GTK_MICRO_VERSION@
-GTK_MINOR_VERSION = @GTK_MINOR_VERSION@
-GTK_PACKAGES = @GTK_PACKAGES@
-GTK_UPDATE_ICON_CACHE = @GTK_UPDATE_ICON_CACHE@
-GTK_VERSION = @GTK_VERSION@
-GTK_XIM_FLAGS = @GTK_XIM_FLAGS@
+BTKDOC_CHECK = @BTKDOC_CHECK@
+BTKDOC_CHECK_PATH = @BTKDOC_CHECK_PATH@
+BTKDOC_DEPS_CFLAGS = @BTKDOC_DEPS_CFLAGS@
+BTKDOC_DEPS_LIBS = @BTKDOC_DEPS_LIBS@
+BTKDOC_MKPDF = @BTKDOC_MKPDF@
+BTKDOC_REBASE = @BTKDOC_REBASE@
+BTK_API_VERSION = @BTK_API_VERSION@
+BTK_BINARY_AGE = @BTK_BINARY_AGE@
+BTK_BINARY_VERSION = @BTK_BINARY_VERSION@
+BTK_DEBUG_FLAGS = @BTK_DEBUG_FLAGS@
+BTK_DEP_CFLAGS = @BTK_DEP_CFLAGS@
+BTK_DEP_LIBS = @BTK_DEP_LIBS@
+BTK_EXTRA_CFLAGS = @BTK_EXTRA_CFLAGS@
+BTK_EXTRA_LIBS = @BTK_EXTRA_LIBS@
+BTK_INTERFACE_AGE = @BTK_INTERFACE_AGE@
+BTK_MAJOR_VERSION = @BTK_MAJOR_VERSION@
+BTK_MICRO_VERSION = @BTK_MICRO_VERSION@
+BTK_MINOR_VERSION = @BTK_MINOR_VERSION@
+BTK_PACKAGES = @BTK_PACKAGES@
+BTK_UPDATE_ICON_CACHE = @BTK_UPDATE_ICON_CACHE@
+BTK_VERSION = @BTK_VERSION@
+BTK_XIM_FLAGS = @BTK_XIM_FLAGS@
 HAVE_HTTP_AUTHSTRING = @HAVE_HTTP_AUTHSTRING@
 HTML_DIR = @HTML_DIR@
 INCLUDED_IMMODULE_DEFINE = @INCLUDED_IMMODULE_DEFINE@
@@ -333,7 +333,7 @@ PACKAGE_STRING = @PACKAGE_STRING@
 PACKAGE_TARNAME = @PACKAGE_TARNAME@
 PACKAGE_URL = @PACKAGE_URL@
 PACKAGE_VERSION = @PACKAGE_VERSION@
-PANGO_PREFIX = @PANGO_PREFIX@
+BANGO_PREFIX = @BANGO_PREFIX@
 PATH_SEPARATOR = @PATH_SEPARATOR@
 PERL = @PERL@
 PKG_CONFIG = @PKG_CONFIG@
@@ -386,9 +386,9 @@ datarootdir = @datarootdir@
 docdir = @docdir@
 dvidir = @dvidir@
 exec_prefix = @exec_prefix@
-gdktarget = @gdktarget@
-gdktargetlib = @gdktargetlib@
-gtktargetlib = @gtktargetlib@
+bdktarget = @bdktarget@
+bdktargetlib = @bdktargetlib@
+btktargetlib = @btktargetlib@
 host = @host@
 host_alias = @host_alias@
 host_cpu = @host_cpu@
@@ -418,8 +418,8 @@ target_alias = @target_alias@
 top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
-GTESTER = gtester		# in $PATH for non-GLIB packages
-GTESTER_REPORT = gtester-report		# in $PATH for non-GLIB packages
+BTESTER = btester		# in $PATH for non-BUNNYLIB packages
+BTESTER_REPORT = btester-report		# in $PATH for non-BUNNYLIB packages
 
 # initialize variables for unconditional += appending
 EXTRA_DIST = README marshalers.list typebuiltins.c.template \
@@ -437,42 +437,42 @@ XIDS = 101 102 103 104 105 106 107 197 199 211 223 227 293 307 308 309 310 311 \
   9980 9981 9982 9983 9984 9985 9986 9987 9988 9989 9990 9991 9992 9993 9994 \
   9995 9996 9997 9998 9999
 
-SKIP_GDKTARGET = \
-	test "$(gdktarget)" != "x11" \
-	&& echo "Gtk+Tests:INFO: Skipping GUI tests for non-X11 target."
+SKIP_BDKTARGET = \
+	test "$(bdktarget)" != "x11" \
+	&& echo "Btk+Tests:INFO: Skipping GUI tests for non-X11 target."
 
 XVFB_START = \
 	${XVFB} -help 2>/dev/null 1>&2 \
 	&& XID=`for id in $(XIDS) ; do test -e /tmp/.X$$id-lock || { echo $$id; exit 0; }; done; exit 1` \
 	&& { ${XVFB} :$$XID -screen 0 800x600x16 -nolisten tcp -auth /dev/null >/dev/null 2>&1 & \
 	       trap "kill -15 $$! " 0 HUP INT QUIT TRAP USR1 PIPE TERM ; } \
-	|| { echo "Gtk+Tests:ERROR: Failed to start Xvfb environment for X11 target tests."; exit 1; } \
+	|| { echo "Btk+Tests:ERROR: Failed to start Xvfb environment for X11 target tests."; exit 1; } \
 	&& DISPLAY=:$$XID && export DISPLAY
 
 INCLUDES = \
 	-I$(top_srcdir)			\
-	-I$(top_builddir)/gdk		\
-	-I$(top_srcdir)/gdk		\
-	-DGDK_DISABLE_DEPRECATED	\
-	-DGTK_DISABLE_DEPRECATED	\
-	$(GTK_DEBUG_FLAGS)		\
-	$(GTK_DEP_CFLAGS)
+	-I$(top_builddir)/bdk		\
+	-I$(top_srcdir)/bdk		\
+	-DBDK_DISABLE_DEPRECATED	\
+	-DBTK_DISABLE_DEPRECATED	\
+	$(BTK_DEBUG_FLAGS)		\
+	$(BTK_DEP_CFLAGS)
 
 DEPS = \
-	$(top_builddir)/gdk/$(gdktargetlib)				\
-	$(top_builddir)/gtk/$(gtktargetlib)
+	$(top_builddir)/bdk/$(bdktargetlib)				\
+	$(top_builddir)/btk/$(btktargetlib)
 
 LDADDS = \
-	$(top_builddir)/gdk/$(gdktargetlib)				\
-	$(top_builddir)/gtk/$(gtktargetlib)				\
-	$(GTK_DEP_LIBS)
+	$(top_builddir)/bdk/$(bdktargetlib)				\
+	$(top_builddir)/btk/$(btktargetlib)				\
+	$(BTK_DEP_LIBS)
 
 testperf_DEPENDENCIES = $(TEST_DEPS)
 testperf_LDADD = $(LDADDS)
 testperf_SOURCES = \
 	appwindow.c		\
-	gtkwidgetprofiler.c	\
-	gtkwidgetprofiler.h	\
+	btkwidgetprofiler.c	\
+	btkwidgetprofiler.h	\
 	main.c			\
 	marshalers.c		\
 	marshalers.h		\
@@ -493,7 +493,7 @@ stamp_files = \
 	stamp-typebuiltins.h
 
 headers_with_enums = \
-	gtkwidgetprofiler.h
+	btkwidgetprofiler.h
 
 MAINTAINERCLEANFILES = $(BUILT_SOURCES) $(stamp_files)
 all: $(BUILT_SOURCES)
@@ -552,7 +552,7 @@ distclean-compile:
 	-rm -f *.tab.c
 
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/appwindow.Po@am__quote@ # am--include-marker
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/gtkwidgetprofiler.Po@am__quote@ # am--include-marker
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/btkwidgetprofiler.Po@am__quote@ # am--include-marker
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/main.Po@am__quote@ # am--include-marker
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/marshalers.Po@am__quote@ # am--include-marker
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/textview.Po@am__quote@ # am--include-marker
@@ -723,7 +723,7 @@ clean-am: clean-generic clean-libtool clean-noinstPROGRAMS \
 
 distclean: distclean-am
 		-rm -f ./$(DEPDIR)/appwindow.Po
-	-rm -f ./$(DEPDIR)/gtkwidgetprofiler.Po
+	-rm -f ./$(DEPDIR)/btkwidgetprofiler.Po
 	-rm -f ./$(DEPDIR)/main.Po
 	-rm -f ./$(DEPDIR)/marshalers.Po
 	-rm -f ./$(DEPDIR)/textview.Po
@@ -775,7 +775,7 @@ installcheck-am:
 
 maintainer-clean: maintainer-clean-am
 		-rm -f ./$(DEPDIR)/appwindow.Po
-	-rm -f ./$(DEPDIR)/gtkwidgetprofiler.Po
+	-rm -f ./$(DEPDIR)/btkwidgetprofiler.Po
 	-rm -f ./$(DEPDIR)/main.Po
 	-rm -f ./$(DEPDIR)/marshalers.Po
 	-rm -f ./$(DEPDIR)/textview.Po
@@ -824,8 +824,8 @@ uninstall-am:
 test: test-cwd test-recurse
 # test-cwd: run tests in cwd
 test-cwd: ${TEST_PROGS}
-	@$(SKIP_GDKTARGET) || test -z "${TEST_PROGS}" || { \
-	  $(XVFB_START) && { set -e; $(TESTS_ENVIRONMENT) ${GTESTER} --verbose ${TEST_PROGS}; }; \
+	@$(SKIP_BDKTARGET) || test -z "${TEST_PROGS}" || { \
+	  $(XVFB_START) && { set -e; $(TESTS_ENVIRONMENT) ${BTESTER} --verbose ${TEST_PROGS}; }; \
 	}
 # test-recurse: run tests in subdirs
 test-recurse:
@@ -838,15 +838,15 @@ test-recurse:
 # full-report: like test-report: with -m perf and -m slow
 test-report perf-report full-report:	${TEST_PROGS}
 	@ ignore_logdir=true ; \
-	  if test -z "$$GTESTER_LOGDIR" ; then \
-	    GTESTER_LOGDIR=`mktemp -d "\`pwd\`/.testlogs-XXXXXX"`; export GTESTER_LOGDIR ; \
+	  if test -z "$$BTESTER_LOGDIR" ; then \
+	    BTESTER_LOGDIR=`mktemp -d "\`pwd\`/.testlogs-XXXXXX"`; export BTESTER_LOGDIR ; \
 	    ignore_logdir=false ; \
 	  fi ; \
 	  for subdir in $(SUBDIRS) ; do \
 	    test "$$subdir" = "." -o "$$subdir" = "po" -o "$$subdir" = "po-properties" || \
 	    ( cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $@ ) || exit $? ; \
 	  done ; \
-	  $(SKIP_GDKTARGET) || test -z "${TEST_PROGS}" || { \
+	  $(SKIP_BDKTARGET) || test -z "${TEST_PROGS}" || { \
 	    case $@ in \
 	    test-report) test_options="-k";; \
 	    perf-report) test_options="-k -m=perf";; \
@@ -854,23 +854,23 @@ test-report perf-report full-report:	${TEST_PROGS}
 	    esac ; \
 	    $(XVFB_START) && { \
 	      set -e; \
-	      if test -z "$$GTESTER_LOGDIR" ; then \
-	        ${GTESTER} --verbose $$test_options -o test-report.xml ${TEST_PROGS} ; \
+	      if test -z "$$BTESTER_LOGDIR" ; then \
+	        ${BTESTER} --verbose $$test_options -o test-report.xml ${TEST_PROGS} ; \
 	      elif test -n "${TEST_PROGS}" ; then \
-	        ${GTESTER} --verbose $$test_options -o `mktemp "$$GTESTER_LOGDIR/log-XXXXXX"` ${TEST_PROGS} ; \
+	        ${BTESTER} --verbose $$test_options -o `mktemp "$$BTESTER_LOGDIR/log-XXXXXX"` ${TEST_PROGS} ; \
 	      fi ; \
 	    }; \
 	  }; \
 	  $$ignore_logdir || { \
 	    echo '<?xml version="1.0"?>' > $@.xml ; \
 	    echo '<report-collection>'  >> $@.xml ; \
-	    for lf in `ls -L "$$GTESTER_LOGDIR"/.` ; do \
-	      sed '1,1s/^<?xml\b[^>?]*?>//' <"$$GTESTER_LOGDIR"/"$$lf" >> $@.xml ; \
+	    for lf in `ls -L "$$BTESTER_LOGDIR"/.` ; do \
+	      sed '1,1s/^<?xml\b[^>?]*?>//' <"$$BTESTER_LOGDIR"/"$$lf" >> $@.xml ; \
 	    done ; \
 	    echo >> $@.xml ; \
 	    echo '</report-collection>' >> $@.xml ; \
-	    rm -rf "$$GTESTER_LOGDIR"/ ; \
-	    ${GTESTER_REPORT} --version 2>/dev/null 1>&2 ; test "$$?" != 0 || ${GTESTER_REPORT} $@.xml >$@.html ; \
+	    rm -rf "$$BTESTER_LOGDIR"/ ; \
+	    ${BTESTER_REPORT} --version 2>/dev/null 1>&2 ; test "$$?" != 0 || ${BTESTER_REPORT} $@.xml >$@.html ; \
 	  }
 .PHONY: test test-cwd test-recurse test-report perf-report full-report
 # run make test-cwd as part of make check
@@ -880,25 +880,25 @@ marshalers.h: stamp-marshalers.h
 	@true
 
 stamp-marshalers.h: @REBUILD@ marshalers.list
-	$(GLIB_GENMARSHAL) --prefix=_gtk_marshal $(srcdir)/marshalers.list --header >> xgen-gmlh \
+	$(BUNNYLIB_GENMARSHAL) --prefix=_btk_marshal $(srcdir)/marshalers.list --header >> xgen-gmlh \
 	&& (cmp -s xgen-gmlh marshalers.h || cp xgen-gmlh marshalers.h) \
 	&& rm -f xgen-gmlh \
 	&& echo timestamp > $(@F)	
 marshalers.c: @REBUILD@ marshalers.list
-	$(GLIB_GENMARSHAL) --prefix=_gtk_marshal $(srcdir)/marshalers.list --body >> xgen-gmlc \
+	$(BUNNYLIB_GENMARSHAL) --prefix=_btk_marshal $(srcdir)/marshalers.list --body >> xgen-gmlc \
 	&& cp xgen-gmlc marshalers.c \
 	&& rm -f xgen-gmlc
 
 typebuiltins.h: stamp-typebuiltins.h
 	@true
 stamp-typebuiltins.h: @REBUILD@ $(headers_with_enums) typebuiltins.h.template
-	( cd $(srcdir) && $(GLIB_MKENUMS) --template typebuiltins.h.template \
+	( cd $(srcdir) && $(BUNNYLIB_MKENUMS) --template typebuiltins.h.template \
 		$(headers_with_enums) ) >> xgen-gtbh \
 	&& (cmp -s xgen-gtbh typebuiltins.h || cp xgen-gtbh typebuiltins.h ) \
 	&& rm -f xgen-gtbh \
 	&& echo timestamp > $(@F)
 typebuiltins.c: @REBUILD@ $(headers_with_enums) typebuiltins.c.template
-	( cd $(srcdir) && $(GLIB_MKENUMS) --template typebuiltins.c.template \
+	( cd $(srcdir) && $(BUNNYLIB_MKENUMS) --template typebuiltins.c.template \
 		$(headers_with_enums) ) > xgen-gtbc \
 	&& cp xgen-gtbc typebuiltins.c  \
 	&& rm -f xgen-gtbc
